[package]
name = "img-to-ascii-rust"
version = "0.1.0"
edition = "2023"
authors = ["Vasantha Kumar <kvasanth373@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.88.5"

